[package]
name = "cypher-sys"
version = "0.1.0"
#authors = ["noone"]

links = "cypher"
build = "build.rs"

[dependencies]
#libc = "0.1"
libc = "*"

[build-dependencies]
pkg-config = "0.3"
gcc = "0.3"


[features]
evas = []
